In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# Problem definition
J = lambda x : (x[0] - 2)**2 + (x[1] - 4)**2
nVar = 2
VarMin = [-5,-10]
VarMax = [10,8]  
VarSize = np.array([nVar,1])
bounds = np.column_stack((VarMin,VarMax))

In [ ]:
bounds

array([[ -5,  10],
       [-10,   8]])

In [ ]:
class Particle_swarm:
  def __init__(self, J, bounds, VarSize):
    self.position = np.random.uniform(bounds[:, 0], bounds[:, 1]).reshape(VarSize)
    self.cost = J(self.position)
    self.velocity = np.zeros(VarSize)
    self.best_position = self.position.copy()
    self.best_cost = self.cost

In [ ]:
class GlobalPractice:
  def __init__(self):
    self.cost = np.inf
    self.position = []

In [ ]:
# Parameters of PSO
W = 1
c1 = 2
c2 = 2
nPop = 50
MaxIt = 100
GlobalBest = GlobalPractice()
particle = [None] * nPop

In [ ]:
for i in range(nPop):
  particle[i] = Particle_swarm(J, bounds, VarSize)
  if particle[i].cost < GlobalBest.cost:
    GlobalBest.position = particle[i].position.copy()
    GlobalBest.cost = particle[i].cost

In [ ]:
for iter in range(MaxIt):
    for i in range(nPop):
        # Update particles’ velocities.
        particle[i].velocity = W * particle[i].velocity +\
                              np.random.rand() * c1 * (particle[i].best_position - particle[i].position) +\
                              np.random.rand() * c2 * (GlobalBest.position - particle[i].position)                              
        
        # Move particles to their new positions.
        particle[i].position = particle[i].position + particle[i].velocity
      
        # if the position is out of boundries replace position with boundries
        particle[i].position = np.maximum(bounds[:, 0].reshape(-1, 1), np.minimum(bounds[:, 1].reshape(-1, 1), particle[i].position))
        
        # Update cost function
        particle[i].cost = J(particle[i].position)

        # If a particle’s present position is better than its previous best position, update it.
        if particle[i].cost < particle[i].best_cost:
          particle[i].best_cost = particle[i].cost
          particle[i].best_position = particle[i].position.copy()

          # If a particle’s present position is better than Global best position, update it.
          if particle[i].cost < GlobalBest.cost:
            GlobalBest.cost = particle[i].cost
            GlobalBest.position = particle[i].position.copy()


In [ ]:
GlobalBest.cost

array([0.00022635])

In [ ]:
GlobalBest.position

array([[2.00205952],
       [4.01490342]])